-- =============================================================
--  合成大西瓜 · 2.0 升级迁移脚本（Supabase / PostgreSQL）
-- =============================================================
--  用法：复制全部内容到 Supabase 项目 → SQL Editor → New query → Run
--  说明：本脚本是**幂等**的，可重复执行，不会丢历史数据
--  影响：
--    - 1.0 老用户：旧纪录自动归入「全服榜(classic)」
--    - 2.0 新功能：排行榜双模式（classic / power）
-- =============================================================

-- ---------- 路径 A：1.0 老表，升级到 2.0 ----------
-- 加 mode 列（不存在才加），默认 'classic'，旧数据自动归入全服榜
alter table score
  add column if not exists mode text not null default 'classic';

-- 删除旧的 name 唯一约束（如果有），换成 (name, mode) 联合唯一
-- 同一玩家在两榜上可以有同名但不同模式的两条记录
alter table score
  drop constraint if exists score_name_key;

create unique index if not exists score_name_mode_key
  on score(name, mode);

-- ---------- 路径 B：全新项目，2.0 直接建表 ----------
-- 如果你还没有 score 表，可以单独跑这段（或整段都跑也安全）
/*
create table if not exists score(
  id bigint generated by default as identity primary key,
  name text not null,
  score int not null default 0 check (score between 0 and 999999),
  mode text not null default 'classic',          -- classic=全服榜(纯净) / power=道具挑战榜
  created_at timestamptz default now()
);

alter table score enable row level security;

create policy "anon_ins" on score for insert to anon with check (true);
create policy "anon_sel" on score for select to anon using (true);

grant usage on schema public to anon;
grant select, insert on table score to anon;
*/

-- ---------- 完成后自检（可选，手动跑）----------
-- select mode, count(*) from score group by mode;
-- 应该看到 classic 有历史数据 + power 出现新数据
